In [1]:
import os
import pandas as pd
from scipy.sparse import coo_array

In [2]:
df = pd.read_csv("/data6/deepro/ukb_bmi/0_data_preparation_and_download/genotype/data/processed_burden/all_gene_burden.csv.gz", usecols=["gene", "samples"])

In [3]:
def get_sparse_df(df):
    df["samples"] = df.samples.str.split(",")
    df = df.explode("samples")
    samples_index = {s:i for i,s in enumerate(df.samples.unique())}
    gene_index = {g:i for i,g in enumerate(df.gene.unique())}
    row_index = df.samples.map(samples_index)
    col_index = df.gene.map(gene_index)
    data = [1 for i in range(len(row_index))]
    sparse_arr = coo_array((data, (row_index, col_index)), shape=(len(samples_index), len(gene_index)))
    df = pd.DataFrame.sparse.from_spmatrix(sparse_arr, index=samples_index.keys(), columns=gene_index.keys())
    return df

In [4]:
sparse_df = get_sparse_df(df)

In [12]:
df.memory_usage().sum() / 1e6

0.352084

In [13]:
sparse_df.memory_usage().sum() / 1e6

611.161528

In [15]:
sparse_df

,5S_rRNA,7SK,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,...,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3,hsa,snoZ196
1930029,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3573775,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3689467,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5679353,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3793132,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3251227,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5881779,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2452425,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2048684,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4846341,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0